# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/haris78866"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Email"
name = "Mail"
url = "(mailto:ariainharis151@gmail.com)"

[social.params]
icon = "brand-email"

[[social]]
identifier = "Whats app"
name = "Whats-app"
url = "[Call me](tel:+923486580072)"

[social.params]
icon = "brand-Whats-app"